[workspace]
channels = ["https://prefix.dev/pixi-build-backends", "https://prefix.dev/conda-forge", "https://prefix.dev/robostack-jazzy"]
platforms = ["osx-arm64", "linux-64"]
preview = ["pixi-build"]

[activation.env]
RMW_IMPLEMENTATION="rmw_cyclonedds_cpp"

[tasks]
py-server = "ros2 run action_tutorials_py fibonacci_action_server"
py-client = "ros2 run action_tutorials_py fibonacci_action_client"
cpp-server = "ros2 run action_tutorials_cpp fibonacci_action_server"
cpp-client = "ros2 run action_tutorials_cpp fibonacci_action_client"

[dependencies]
# Needed for testing purpose
pixi-build-api-version = { path = "~/dev/pixi-build-backends/recipe/pixi-build-api-version" }

ros-jazzy-action-tutorials-cpp = {  path = "action_tutorials/action_tutorials_cpp" }
#ros-jazzy-action-tutorials-py = "*"
ros-jazzy-action-tutorials-py = { path = "action_tutorials/action_tutorials_py" }
ros-jazzy-desktop = "*"
