[package] 
name = "ros-jazzy-action-tutorials-cpp"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-ros", path = "/Users/rubenarts/dev/pixi-build-backends/backends/pixi-build-ros" } 
configuration = { distro = "jazzy" }
